version: '3.8'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    networks:
      - sonarnet

  nginx:
    image: nginx:latest
    container_name: sonarqube_nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sonarnet

networks:
  sonarnet:
    driver: bridge
