name: AzureStaticWebAppDeployment

on:
  push:
    branches:
      - main

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Repository Name
        id: repo_name
        run: echo "::set-output name=name::${{ github.event.repository.name }}"

      - name: Create Azure Storage Container
        run: |
          az storage container create --name ${{ steps.repo_name.outputs.name }} --account-name storagemicrofrontend

      - name: Upload dist files to Azure Storage
        run: |
          az storage blob upload-batch --account-name storagemicrofrontend --destination modern -s dist --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name cdn-microfrontend1 --name endpoint-microfrontend1 --resource-group microfrontendgroup

      - name: Logout Azure
        run: |
          az logout
        if: always()
