name: Lighthouse
on:
  push:
    branches:
      - main

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install CLI dependencies
        run: npm install

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.3.x

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.3.x
          npm run lighthouse:ci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
