name: site-security-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Checkout code from the repository
      - name: Install ZAP
        run: sudo apt update && sudo apt install zaproxy
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0  # Update to the latest stable version
        with:
          target: "https://www.bing.com/"
          # Add other ZAP Baseline action options here (e.g., fail_action)
