name: OWASP ZAP Full Scan Integration without Docker

on:
  push:

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Perform OWASP ZAP Full Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2_11_1_unix.sh
          chmod +x ZAP_2_11_1_unix.sh
          sudo ./ZAP_2_11_1_unix.sh -q

      - name: Run OWASP ZAP Full Scan
        run: |
          /opt/ZAP_2.11.1/zap.sh -daemon -config api.disablekey=true &
          sleep 10 # Give ZAP a few seconds to start
          wget -O zap-full-scan.py https://raw.githubusercontent.com/zaproxy/zap-admin/master/docker/zap-full-scan.py
          python3 zap-full-scan.py -t http://testphp.vulnweb.com -r report_html.html -w report_md.md -J report_json.json -t 300

      - name: Upload ZAP Scan Report
        if: always() # Ensure this runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: zap_scan_report
          path: report_html.html
