name: OWASP ZAP Full Scan Integration with GitHub Actions

on:
  push:

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    name: Perform OWASP ZAP Full Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://testphp.vulnweb.com' # Ensure this URL is correct
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: true # Set to true to fail the action if any alerts are found
          cmd_options: '-t 300' # Optional: Set timeout to 300 seconds

      - name: Upload ZAP Scan Report
        if: always() # Ensure this runs even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: zap_scan_report
          path: report_html.html
